export const DHA = [
  "Healthcare Services which are not medically necessary",
  "All expenses relating to dental treatment, dental prostheses, and orthodontic treatments",
  "Care for the sake of travelling",
  "Custodial care including: Non-medical treatment services, Health-related services which do not seek to improve or which do not result in a change in the medical condition of the patient.",
  "Services which do not require continuous administration by specialized medical personnel.",
  "Personal comfort and convenience items (television, barber or beauty service, guest service and similar incidental services and supplies).",
  "All cosmetic healthcare services and services associated with replacement of an existing breast implant. Cosmetic operations which are related to an Injury, sickness or congenital anomaly when the primary purpose is to improve physiological functioning of the involved part of the body and breast reconstruction following a mastectomy for cancer are covered.",
  "Experimental or investigational drugs and treatments.",
  "Treatments for obesity or weight control.",
  "Fertility treatments, contraception, and sterilization.",
  "Healthcare services and associated expenses for the treatment of alopecia, baldness, hair falling, dandruff or wigs.",
  "Health services and supplies for smoking cessation programs and the treatment of nicotine addiction.",
  "Treatment and services for contraception",
  "ment and services for sex transformation, sterilization or intended to correct a state of sterility or infertility or sexual dysfunction. Sterilization is allowed only if medically indicated and if allowed under the Law",
  "External prosthetic devices and medical equipment",
  "Treatments and services arising as a result of professional sports activities, including but not limited to, any form of aerial flight, any kind of power-vehicle race, water sports, horse riding activities, mountaineering activities, violent sports such as judo, boxing, and wrestling, bungee jumping and any professional sports activities",
  "Growth hormone therapy unless medically necessary",
  "Costs associated with hearing tests, prosthetic devices or hearing and vision aids",
  "Patient treatment supplies (including for example: elastic stockings, ace bandages, gauze, syringes, diabetic test strips, and like products; non-prescription drugs and treatments,) excluding supplies required as a result of Healthcare Services rendered during a Medical Emergency",
  "Allergy testing and desensitization (except testing for allergy towards medications and supplies used in treatment); any physical, psychiatric or psychological examinations or investigations during these examinations.",
  "Services rendered by any medical provider who is a relative of the patient for example the Insured person himself or first degree relatives.",
  "Enteral feedings (via a tube) and other nutritional and electrolyte supplements, unless medically necessary during in-patient treatment.",
  "Healthcare services for adjustment of spinal subluxation.",
  "Healthcare services and treatments by acupuncture; acupressure, hypnotism, massage therapy, aromatherapy, ozone therapy, and all forms of treatment by alternative medicine except Homeopathy and Ayurveda.",
  "All healthcare services & treatments for in-vitro fertilization (IVF), embryo transfer; ovum and sperms transfer.",
  "Elective diagnostic services and medical treatment for correction of vision",
  "Nasal septum deviation and nasal concha resection.",
  "All chronic conditions requiring hemodialysis or peritoneal dialysis, and related investigations, treatments or procedures.",
  "Any services related to Birth defects, congenital diseases and deformities unless if left untreated will develop into an emergency.",
  "Healthcare services for senile dementia and Alzheimer's disease.",
  "Air or terrestrial medical evacuation and unauthorized transportation services.",
  "Inpatient treatment received without prior approval from the insurance company including cases of medical emergency which were not notified within 24 hours from the date of admission where possible.",
  "Any inpatient treatment, investigations or other procedures, which can be carried out on outpatient basis without jeopardizing the Insured Person's health.",
  "Any investigations or health services conducted for non-medical purposes such as investigations related to employment, travel, licensing or insurance purposes.",
  "All supplies which are not considered as medical treatments including but not limited to: mouthwash, toothpaste, lozenges, antiseptics, food supplements, skin care products, shampoos and multivitamins (unless prescribed as replacement therapy for known vitamin deficiency conditions); and all equipment not primarily intended to improve a medical condition or injury, including but not limited to: air conditioners or air purifying systems, arch supports, exercise equipment and sanitary supplies.",
  "More than one consultation or follow up with a medical specialist in a single day unless referred by the treating physician.",
  "Health services and associated expense for organ and tissue transplants for donor. This exclusion also applies to follow up treatments and complications unless if left untreated will develop into an emergency ",
  "Any expenses related to immunomodulators and immunotherapy unless medically necessary.",
  "Any expenses related to the treatment of sleep related disorders.",
  "Services and educational programs for   people of determination, this also includes disability types such as but not limited to mental, intellectual, developmental, physical and/or psychological disabilities. ",
  "Any treatment required as a result of hospital acquired infections",
  "Services and educational programs for people of determination, this also includes disability types such as but not limited to mental, intellectual, developmental, physical and/or psychological disabilities.",
  "Injuries or illnesses suffered by the Insured Person as a result of military operations of whatever type.",
  "Injuries or illnesses suffered by the Insured Person as a result of wars or acts of terror of whatever type.",
  "Healthcare services for injuries and accidents arising from nuclear or chemical contamination.",
  "Injuries resulting from natural disasters, including but not limited to: earthquakes, tornados and any other type of natural disaster.",
  "Injuries resulting from criminal acts or resisting authority by the Insured Person.",
  "Injuries resulting from a road traffic accident.",
  "Healthcare services for work related illnesses and injuries as per Federal Law No. 8 of 1980 concerning the Regulation of Work Relations, its amendments, and applicable laws in this respect.",
  "All cases resulting from the use of alcoholic drinks, controlled substances and drugs and hallucinating substances.",
  "Any investigation or treatment not prescribed by a doctor.",
  "Injuries resulting from attempted suicide or self-inflicted injuries.",
  "Diagnosis and treatment services for complications of exempted illnesses.",
  "All healthcare services for internationally and/or locally recognized epidemics.",
  "Healthcare services for patients suffering from (and related to the diagnosis and treatment of) HIV - AIDS and its complications and all types of hepatitis except virus A and C hepatitis.",
];

export const HAAD = [
  "Healthcare Services, which are not medically necessary",
  "Al expenses relating to dental treatment, dental prostheses, and orthodontic treatments excluding treatment necessitated by traumatic and violent injury.",
  "Custodial care; domiciliary care; private duty nursing; respite care; rest cures. Custodial care means (1) non-health related services, such as assistance in activities of daily living, or (2) health-related services which do not seek to cure or which are provided during periods when the medical condition of the patient is not changing or (3) services which do not require continued administration by trained medical personnel.",
  "Personal comfort and convenience items or services including but not restricted to television, telephone, bather or beauty service, guest service and similar incidental services and supplies.",
  "Healthcare services and associated expenses for cosmetic procedures. Cosmetic procedures are those procedures which improve physical appearance and which are not incidental to an Injury, sickness or congenital anomaly when the primary purpose is to improve physiological functioning of the involved part of the body. Breast reconstruction following a mastectomy for cancer is covered.",
  "Replacement of an existing breast implant.",
  "Treatment for alopecia, baldness, hair falling, dandruff, wigs, or toupees.",
  "Treatment and services for smoking cessation programs and the treatment of nicotine addiction.",
  "Surgical and non-surgical treatment for obesity (including morbid obesity), and any other weight control programs, services, or supplies.",
  "Experimental, investigational or unproven healthcare services, treatments, devices and pharmacological regimens, the fact that an experimental, investigational or unproven healthcare service, treatment, device or pharmacological regimen is the only available treatment for a particular condition will not result in coverage under a Health Insurance Policy without prior approval of the Authorized Insurer.",
  "Healthcare Services, apart from Healthcare Services rendered in a Medical Emergency that are not performed by Authorized Providers without prior approval of the Authorized Insurer.",
  "Treatment and services for any drug addiction or substance abuse or addiction.",
  "Amniocentesis except where certified by a medical practitioner to be medically necessary.",
  "Treatment and services for sex transformation operations, voluntary sterilization and for reversal of sterilizations.",
  "Treatment and services for contraceptive supplies or services.",
  "Treatment and services related to fertility/infertility including varicocele or polycystic ovary/ ovarian cyst or hormonal disturbances, and sexual dysfunction.",
  "Treatment of venereal diseases medically accepted to be transmitted by intercourse.",
  "Except where certified by a medical practitioner to be medically necessary, prosthetic devices and durable medical equipment, comprising medical equipment used externally from the human body which:",
  "can withstand repeated use;",
  "is not designed to be disposable;",
  "is used to serve a medical purpose;",
  "is generally not useful to a person in the absence of a sickness or injury; and ",
  "is used outside of a hospital",
  "Treatments and services arising as a result of hazardous activities, including but not limited to:",
  "Any form of aerial flight (including light aircraft, monoplanes, ballooning, hang-gliding, parachuting)",
  "Participation in any kind of power-vehicle race, rally or competition",
  "Water sports (powerboats, Water skiing, jet skiing, diving)",
  "Horse riding activities (hunting, jumping, polo, racing)",
  "Climbing activities (mountaineering, rock-climbing, pot holing, abseiling)",
  "Judo, boxing, karate, wrestling and other martial arts of any kind.",
  "Bungee jumping",
  "Any professional sports activities",
  "Growth hormone therapy.",
  "Terrestrial transportation in cases other than Medical Emergencies.",
  "Transportation by means other than local licensed ambulance services.",
  "Air ambulance transportation.",
  "Mental Health diseases, including pharmaceuticals, in-patient and out- patient treatments, unless the condition is a transient mental disorder or an acute reaction to stress.",
  "Outpatient prescribed or non-prescribed medical supplies including elastic stockings, ace bandages gauze, syringes, diabetic test strips, and like products; non-prescription drugs and treatments, excluding such supplies required as a result of Healthcare Services rendered during medical emergency.",
  "All preventative and routine processes, including vaccinations, immunizations, allergy, testing and desensitization; any physical, psychiatric or psychological examinations or testing during these examinations, except where such treatments or services are required in connection with the provision of Healthcare Services.",
  "Services rendered by any medical provider with the same legal residence as an    Insured Person or who is a member of an Insured Person's family, including spouse, brother, sister, parent or child.",
  "Enteral feedings (infusion formulas via a tube into the upper gastrointestinal tract) and other nutritional and electrolyte supplements, unless medically necessary to be performed in conjunction with Healthcare Services that are covered under a Health Insurance Policy.",
  "All medical treatments and services for an otherwise eligible person to whom the Health Insurance Law applies, together with his spouse and children, who is on active military duty.",
  "Treatment and services for the analysis and adjustment of spinal subluxation, diagnosis and treatment by manipulation of the skeletal structure, or for muscle stimulation by any means, except treatment of fractures and dislocations of the extremities.",
  "Treatments and services for acupuncture; acupressure, hypnotism, rolfing, massage therapy, aromatherapy, homeopathic treatments, and other forms of alternative treatment.",
  "Treatments and services for in-vitro fertilization (VF), gamete intra-fallopian transfer (GIFT) procedures, and zygote intrafallopian transfer (ZIFT) procedures, and any related prescription medication treatment; embryo transport; donor ovum and semen and related costs, including collection and preparation.",
  "Elective non-accident related surgery for correction of refraction errors and/or improvement of vision (quantitative or qualitative), including but not limited to radial keratotomy, photokeratectomy or laser surgery.",
  "Nasal septum deviation and nasal concha resection.",
  "All conditions requiring hemodialysis or peritoneal dialysis, and related test/treatment or procedure.",
  "Any healthcare services and associated expenses for HIV, AIDS and all related medical conditions, following confirmation of diagnosis.",
  "Treatments and services related to viral hepatitis and associated complications, except for treatment and services related to Hepatitis A.",
  "Birth defects, Congenital diseases &/or Deformities unless life-threatening.",
  "All cases resulting from alcoholism, use of drugs and/or hallucinatory substances.",
  "Senile dementia and Alzheimer's disease",
  "All medical costs resulting from work related accidents, medical condition or sickness that is covered by workers' compensation provisions (or any similar program).",
  "Circumcision and any complications or related expenses.",
  "All cases related to maternity in respect of unmarried females.",
  "Any inpatient treatment, tests and other procedures, which can be carried out on outpatient basis without jeopardizing the Insured Person's health.",
  "Any test or treatment, which is not related to a specific symptom and/or disease.",
  "Any pharmaceutical products which are not considered as specific treatment for a particular disease or medical condition, including examinations required for employment, travel, immigration, licensing or insurance and related reports.",
  "All substances which are not. considered as medical treatments including but not limited to: mouthwash, toothpaste, lozenges, antiseptics, milk formulas, food supplements, skin care products, shampoos and multivitamins (unless prescribed as replacement therapy for known vitamin deficiency conditions) and all equipment not primarily intended to improve a medical condition or injury, including, but not limited to air conditioners or air purifying systems, arch supports, convenience items 1 options, exercise equipment and sanitary supplies.",
  "More than one consultation with a medical practitioner in a single day for Healthcare Services or follow-up consultations where not certified by a medical practitioner to be medically necessary.",
  "Lesions resulting from attempted suicides or self-inflicted non-accidental injuries.",
  "Health services and associated expenses for organ and tissue transplants, irrespective of whether the Insured Person is a donor or recipient.",
  "Complications directly arising from excluded Healthcare Services.",
  "All kind of educational programs and/or learning disabilities treatments.",
  "Criminal actions of an Insured Person, including the violation or attempted violation of the law and resistance to lawful arrest or any resultant imprisonment.",
  "Officially recognized epidemics and pandemics.",
  "Naval or military operations of the armed forces or air force and participation in operations requiring the use of arms or which are ordered by military authorities for combating terrorists, rebels and the like.",
  "Wars and circumstances comparable with a state of war, invasion, act by a foreign enemy, hostilities and warlike events (with or without a declaration of war), civil war, riot, mutiny, revolution, confiscation or nationalization by order of any public or local government or authority; any act of a person acting in the name of or in connection with any organization whose activities aim to overturn a de lure or de facto government violently",
  "Nuclear risks: e.g. exposure to nuclear energy (nuclear reactions, radiations, contamination) or nuclear waste of any type or chemical contamination.",
  "Natural catastrophes including but not limited to avalanches, earthquakes, volcanic eruptions, tsunamis, hurricanes, tornados or any other kind of natural hazard.",
  "Any act of terrorism, which shall mean an act, including but not limited to the force or violence and/or the threat thereof, of any person or group(s) of persons, whether acting alone or on behalf of or in connection with any organization(s) or government(s), committed for political, religious, ideological, or ethnic purposes or reasons including the intention to influence any government and/or to put the public, or any section of the public, in fear.",
  "Sleep Apnea and sleep studies",
  "All healthcare services for internationally and locally recognized epidemics",
];
